config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: redirect("/products")

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'discounts', to: 'products#index', as: 'discounted_products', scope: 'discounted'

  get 'archives', to: 'products#index', as: 'archived_products', archived: true, scope: "archived"
  get ':category', to: 'products#index', as: 'products_by_category',
    constraints: { category: /#{Product.categories.keys.join('|')}/ }
  
  resources :products do
    patch 'archive', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  enum :category => %i[ beverage food toys ]

  validates :title, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  validates :category, inclusion: { in: categories.keys }

  scope :discounted, -> { where(discounted: true) }
  scope :archived, -> { where.not(archived_at: nil) }
  scope :active, -> { where(archived_at: nil) }

  def discounted_price
    (0.8*price).round(2)
  end

  def archive!
    touch(:archived_at)
  end

  def archived?
    archived_at?
  end

  # def active

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update archive destroy ]

  # GET /products or /products.json
  def index
    @products = Product.order(:title).where(archived_at: nil)
    
    if params[:scope] == "discounted"
      @products = @products.discounted
    end
    if category = params[:category]
      @products = @products.where(category: category)
    end
    pp params[:scope]
    if params[:scope] == "archived"
      @products = Product.order(:title)
      @products = @products.archived
    else
    #   @products.where(archived_at: nil)
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1/archive or /products/1/archive.json
  def archive
    @product.archive!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully archived." }
      format.json { head :no_content }
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy()
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :discounted, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <%= link_to "New product", new_product_path %> |
    <%= link_to "Archived products", archived_products_path %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>New Year's Shop</h1>
  <nav>
    <%= link_to 'All', products_path %>
    <%= link_to 'Discounts 💥', "/discounts" %>
    <% Product.categories.keys.each do |category| %>
      <%= link_to t("product.category.#{category}"), products_by_category_path(category: category) %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New Year's Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <% if notice %>
        <p class='notice' style="color: green"><%= notice %></p>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <p>
        <strong>
          <%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:
        </strong>
      </p>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </p>

  <p>
    <%= form.label :discounted %>
    <%= form.check_box :discounted %>
    <mark style='display: block'>
      Dynamically applies a 20% discount to the price. 💥
    </mark>
  </p>

  <p>
    <%= form.label :category %>
    <%= form.select :category, Product.categories.keys.map { |cat| [t("product.category.#{cat}"), cat] } %>
  </p>

  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class='product'>
  <%= link_to product, class: 'title' do %>
    <strong><%= product.title %></strong>
  <% end %>

  <p><%=h product.description %></p>

  <ul>
    <li class='category'>
      <%= t("product.category.#{product.category}") %>
    </li>
    <li class='price'>
      <% if product.discounted %>
        <mark><%= number_to_currency product.price %> 💥</mark>
      <% else %>
        <%= number_to_currency product.price %>
      <% end %>
    </li>
  </ul>
</div>

app/views/products/edit.html.erb
<h2>Editing product</h2>

<%= render "form", product: @product %>

<br/>
<nav>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</nav>

app/views/products/index.html.erb
<div id="products">
  <% @products.each do |product| %>
    <article>
      <%= render product %>
    </article>
  <% end %>

  <p style="text-align: center" class='counter'>
    <%= t('.products_counter', count: @products.count) %>
  </p>
</div>

app/views/products/new.html.erb
<h2>New product</h2>

<%= render "form", product: @product %>

<br/>
<nav>
  <%= link_to "Back to products", products_path %>
</nav>

app/views/products/show.html.erb
<% if @product.archived? %>
  <h3>ARCHIVED</h3>
<% end %>

<%= render @product %>

<br/>
<nav>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>
</nav>

<br/>
<% if !@product.archived? %>
<%= button_to "Archive", [:archive, @product] %>
<% end %>
<%= button_to "Destroy", @product, method: :delete %>